# Jekyll Resume Theme

# Site settings
title: Brandon Hammothe's Resume
email: email@domain.com
description: Resume built in Jekyll
#baseurl: "http://mattcouchman.co.uk/jekyll-resume/"
#url: "http://mattcouchman.co.uk/jekyll-resume/"
name: Brandon Paul Hammothe
job: Software Engineer in Test
location: West Lafayette, IN
languages: Automated Testing and Biometrics
#twitter_username: mattcouchman
github_username:  bhammoth
#codepen_username:  mattcouchman
#email_address: some@email.com

# Build settings
markdown: kramdown
